version: '3.8'

services:
  db:
    image: postgres:15
    container_name: keley-bolos-db
    environment:
      - POSTGRES_DB=keleybolos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5439:5432"